import streamlit as st
import requests
import datetime

# Frontend-only Streamlit UI.
# Backend should be started separately with: uvicorn main:app --reload --port 8000
BASE_URL = "http://localhost:8000"  # Backend endpoint
HEALTH_ENDPOINT = f"{BASE_URL}/health"
REQUEST_TIMEOUT = 60  # seconds

# Page configuration and title section
st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Session state section for chat/message storage
if "messages" not in st.session_state:
    st.session_state.messages = []

# User prompt heading section
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Backend health check section
backend_available = False
backend_status_message = "Checking backend availability..."
try:
    health_response = requests.get(HEALTH_ENDPOINT, timeout=REQUEST_TIMEOUT)
    health_data = health_response.json() if health_response.headers.get("Content-Type", "").startswith("application/json") else {}
    if health_response.status_code == 200 and health_data.get("status") == "ok":
        backend_available = True
        backend_status_message = "Backend is available. You can submit your travel query."
    else:
        backend_status_message = f"Backend health check failed: {health_response.status_code}"
except requests.exceptions.RequestException as e:
    backend_status_message = f"Backend health check failed: {e}"

if backend_available:
    st.success(backend_status_message)
else:
    st.warning(backend_status_message)

# Chat input section for the user
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    if not backend_available:
        st.error("Cannot send request because backend is unavailable.")
    else:
        try:
            # Show thinking spinner while backend processes
            with st.spinner("Bot is thinking..."):
                payload = {"question": user_input}
                response = requests.post(
                    f"{BASE_URL}/query",
                    json=payload,
                    timeout=REQUEST_TIMEOUT,
                )

            if response.status_code == 200:
                answer = response.json().get("answer", "No answer returned.")

                # Format and display the AI travel plan output
                markdown_content = f"""# 🌍 AI Travel Plan

                # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
                # **Created by:** Atriyo's Travel Agent

                ---

                {answer}

                ---

                *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
                """
                st.markdown(markdown_content)
            else:
                st.error("Bot failed to respond: " + response.text)

        except requests.exceptions.Timeout:
            st.error("Request timed out. Please try again later.")
        except requests.exceptions.RequestException as e:
            st.error(f"The response failed due to {e}")